// Cores oficiais e superfícies recorrentes da marca.
const brand = {
  ink: '#101827',
  graphite: '#182235',
  paper: '#F5F2EC',
  violet: '#6C63FF',
  blue: '#91A8FF',
  mist: '#B9C0CC',
} as const;

export const colors = {
  ...brand,
  background: brand.ink,
  backgroundSecondary: brand.graphite,
  highlight: brand.violet,
  neonBlue: brand.blue,
  white: brand.paper,
  textSecondary: brand.mist,
  inkRaised: '#151F31',
  inkHeader: '#141E30',
  inkDeep: '#0D1522',
} as const;

// Pilha tipográfica única utilizada em toda a interface.
export const fonts = {
  primary: '"Instrument Sans", sans-serif',
  heading: '"Instrument Sans", sans-serif',
  ui: '"Instrument Sans", sans-serif',
} as const;

// Pontos de quebra compartilhados entre páginas e componentes.
export const breakpoints = {
  mobileMax: '480px',
  compactMax: '599px',
  tablet: '768px',
  tabletMax: '767px',
  content: '900px',
  contentMax: '899px',
  laptop: '1024px',
  laptopMax: '1023px',
  signaturePointerMax: '1099px',
  servicesWide: '1100px',
  desktopMax: '1279px',
  wide: '1280px',
} as const;

// Larguras, containers e raios recorrentes de layout.
export const layout = {
  containerWidth: 'min(100%, 1440px)',
  containerPaddingInline: 'clamp(1rem, 4vw, 4.5rem)',
  headerInlineWidth: 'min(calc(100% - clamp(2rem, 8vw, 9rem)), 1440px)',
  headerHeight: 'clamp(4.25rem, 5.2vw, 4.75rem)',
  headerNavigationGap: 'clamp(1.15rem, 2.3vw, 2.3rem)',
  footerPaddingBlock: 'clamp(2.5rem, 5vw, 4.5rem)',
  footerContentGap: 'clamp(2rem, 4vw, 4rem)',
  footerNavigationGap: 'clamp(1.1rem, 2vw, 2rem)',
  radii: {
    control: '10px',
    action: '12px',
  },
} as const;

// Entrada de seções que assumem a viewport antes de revelar seu conteúdo.
export const immersiveIntro = {
  titleSize: 'clamp(2.75rem, 5vw, 4.75rem)',
} as const;

// Escalas fluidas e espaçamentos usados na homepage.
export const homepageTokens = {
  sectionPaddingBlock: 'clamp(5rem, 8vw, 8.5rem)',
  sectionPaddingInline: layout.containerPaddingInline,
  editorialContentFrameWidth: '70rem',
  sectionGap: 'clamp(1.5rem, 4vw, 5rem)',
  eyebrowSize: 'clamp(0.75rem, 0.82vw, 0.84rem)',
  eyebrowTracking: '0.075em',
  sectionTitleSize: 'clamp(2.15rem, 3.2vw, 3.55rem)',
  sectionTitleLineHeight: '1',
  sectionTitleTracking: '-0.045em',
  sectionCopySize: 'clamp(1rem, 1.1vw, 1.1rem)',
  sectionCopyLineHeight: '1.65',
  mobileSectionPaddingBlock: 'clamp(4.25rem, 16vw, 5.5rem)',
  headingMarginBottom: 'clamp(3.5rem, 6vw, 6.5rem)',
  copyMaxWidth: '35rem',
  eyebrowMarginBottom: 'clamp(1.25rem, 2vw, 1.75rem)',
  sectionCopyMarginTop: 'clamp(1.5rem, 2.5vw, 2.25rem)',
  hero: {
    sectionPadding: 'clamp(7.25rem, 10vw, 9.5rem) clamp(1rem, 4vw, 4.5rem) clamp(3.25rem, 6vw, 6rem)',
    compactPaddingTop: 'clamp(6.25rem, 9vw, 7rem)',
    compactPaddingBottom: 'clamp(2rem, 4vw, 3rem)',
    lightSize: 'clamp(22rem, 48vw, 60rem)',
    gridSize: 'clamp(32px, 4vw, 64px)',
    contentGap: 'clamp(2rem, 5vw, 6rem)',
    eyebrowMarginBottom: 'clamp(1.15rem, 2vw, 1.65rem)',
    titleSize: 'clamp(3rem, 6vw, 6.25rem)',
    titleLineHeight: '0.94',
    titleTracking: '-0.067em',
    copyMarginTop: 'clamp(1.4rem, 2.4vw, 2rem)',
    copySize: 'clamp(1rem, 1.15vw, 1.125rem)',
    actionsMarginTop: 'clamp(1.75rem, 3vw, 2.5rem)',
    visualWideWidth: 'clamp(420px, 43vw, 620px)',
    visualLaptopWidth: 'clamp(380px, 48vw, 620px)',
    visualTabletWidth: 'clamp(44vw, 54vw, 60vw)',
    visualMobileWidth: 'clamp(105vw, 118vw, 130vw)',
    lowHeightMax: '820px',
    lowHeightPaddingTop: `calc(${layout.headerHeight} + 1.5rem)`,
    lowHeightPaddingBottom: '2rem',
    lowHeightInnerMinHeight: `calc(100svh - ${layout.headerHeight} - 3.5rem)`,
  },
  services: {
    sectionTitleSize: 'clamp(2.9rem, 4.15vw, 4.35rem)',
    sectionTitleCompactSize: 'clamp(2.55rem, 7.5vw, 2.9rem)',
    serviceTitleSize: 'clamp(2.25rem, 3vw, 3.35rem)',
    serviceTitleMobileSize: 'clamp(2rem, 6.8vw, 2.45rem)',
    scopeSize: 'clamp(0.8rem, 0.88vw, 0.92rem)',
    introTrackHeight: '160svh',
    introTrackMobileHeight: '150svh',
    introStageHeight: `calc(100svh - ${layout.headerHeight})`,
    introStageTop: layout.headerHeight,
    introContentMaxWidth: '70rem',
    introGridGap: 'clamp(1.5rem, 3vw, 3rem)',
    introHeadlineMaxWidth: '15ch',
    introSupportMaxWidth: '28rem',
    introSupportSize: 'clamp(1.08rem, 1.35vw, 1.3rem)',
    introPrimaryExitX: '-4%',
    introSupportExitX: '5%',
    introContentOverlap: '-22svh',
    introContentMobileOverlap: '-18svh',
    compositionsGap: 'clamp(5rem, 7.5vw, 7rem)',
    compositionsMobileGap: 'clamp(4rem, 15vw, 5rem)',
    offerGap: 'clamp(1.5rem, 2.5vw, 2.25rem)',
    offerContentWidth: 'min(100%, 76rem)',
    offerCopyMaxWidth: '32rem',
    offerRevealDistance: 24,
    offerRevealMobileDistance: 10,
    descriptionMarginTop: 'clamp(1.3rem, 2vw, 1.8rem)',
    scopeMarginTop: 'clamp(1.05rem, 1.5vw, 1.4rem)',
    mediaAspectRatio: '16 / 9',
    mediaMobileLandscapeAspectRatio: '16 / 9',
    mediaMobilePortraitAspectRatio: '4 / 3',
    mediaScale: '82%',
    mediaBackdropWidth: '8%',
    mediaBackdropHeight: '36%',
    mediaBackdropBottom: '8%',
    mediaBackdropProjection: '-1.25%',
    mediaBackdropMobileWidth: '10%',
    mediaBackdropMobileHeight: '22%',
    mediaBackdropMobileBottom: '-1%',
    institutionalMediaInset: 'clamp(1rem, 1.75vw, 1.5rem)',
    mediaStackMaxWidth: '52rem',
    mediaFrameRadius: '0.65rem',
    mediaFrameBorder: '1px solid rgba(16, 24, 39, 0.25)',
    mediaChromeHeight: '1.25rem',
    mediaChromeMobileHeight: '1rem',
    mediaChromeBorder: '1px solid rgba(245, 242, 236, 0.1)',
    mediaControlSize: '0.28rem',
    mediaLayerOffset: '0.55rem',
    mediaLayerMobileOffset: '0.4rem',
    mediaLayerBorder: '1px solid rgba(108, 99, 255, 0.18)',
    mediaLayerShadow: '0 0.65rem 1.5rem rgba(16, 24, 39, 0.055)',
    mediaShadowInitial: '0 1px 2px rgba(16, 24, 39, 0.07), 0 0.35rem 0.8rem rgba(16, 24, 39, 0.045)',
    mediaShadow: '0 1px 2px rgba(16, 24, 39, 0.14), 0 0.7rem 1.5rem rgba(16, 24, 39, 0.1), 0 2.1rem 4.5rem rgba(16, 24, 39, 0.095)',
    mediaAccentWidth: '18%',
    mediaRevealInset: '26%',
    mediaRevealDistance: '0.75rem',
    offerRevealAmount: 0.22,
    supportMarginTop: 'clamp(4.75rem, 7vw, 6.75rem)',
    supportPaddingTop: 'clamp(3rem, 5vw, 4.75rem)',
    supportContentMaxWidth: '52rem',
    supportGridGap: 'clamp(1.5rem, 2.5vw, 2rem)',
    supportTitleSize: 'clamp(2.35rem, 3.4vw, 3.65rem)',
    supportTitleMaxWidth: '15ch',
    supportCopyMaxWidth: '23rem',
    supportCopyWeight: 520,
    supportContinuitiesMaxWidth: '56rem',
    supportContinuitiesMarginTop: 'clamp(2.75rem, 4vw, 3.5rem)',
    supportContinuitiesGap: 'clamp(2rem, 4vw, 3.75rem)',
    supportContinuityMarkerSize: '0.625rem',
    supportAccentWidth: 'clamp(4rem, 8vw, 7rem)',
    supportRevealDistance: 12,
    supportTerminalTop: 'clamp(7.5rem, 16svh, 9rem)',
    supportTerminalRunway: '36svh',
  },
  valueProposition: {
    sectionPaddingTop: 'clamp(5rem, 7.5vw, 7.5rem)',
    sectionPaddingBottom: 'clamp(7rem, 11vw, 11rem)',
    introMaxWidth: '68rem',
    titleSize: 'clamp(2.8rem, 4.1vw, 4.4rem)',
    titleRowGap: 'clamp(0.35rem, 0.75vw, 0.65rem)',
    structureOffset: '13.5%',
    descriptionMaxWidth: '39rem',
    descriptionMarginTop: 'clamp(1.65rem, 2.5vw, 2.25rem)',
    primaryPlaneSize: 'clamp(36rem, 64vw, 66rem)',
    secondaryPlaneSize: 'clamp(26rem, 48vw, 48rem)',
    differentiatorsBridgeMarginTop: 'clamp(2.25rem, 3.5vw, 3rem)',
    differentiatorsMarginTop: 'clamp(1.75rem, 2.8vw, 2.35rem)',
    differentiatorsTerminalTop: 'clamp(7.5rem, 16svh, 9rem)',
    differentiatorsTerminalRunway: '45svh',
    differentiatorsMaxWidth: '64rem',
    differentiatorsRowGap: 'clamp(2.35rem, 3.5vw, 3rem)',
    differentiatorsColumnGap: 'clamp(3rem, 5vw, 4.25rem)',
    differentiatorsMobileMaxWidth: '34rem',
    differentiatorsMobileGap: 'clamp(1.8rem, 7vw, 2.4rem)',
    differentiatorMarkerSize: '0.68rem',
    differentiatorTitleSize: 'clamp(1.36rem, 1.55vw, 1.62rem)',
    differentiatorCopySize: 'clamp(1rem, 1.12vw, 1.07rem)',
    differentiatorCopyMaxWidth: '28.5rem',
  },
  projects: {
    transitionPaddingTop: 'clamp(0.75rem, 1.5vw, 1.5rem)',
    stageScrollLength: '385svh',
    mobileStageScrollLength: '300svh',
    stageContentWidth: 'min(100%, 76rem)',
    stageMediaHeight: 'min(70vh, 47rem)',
    stageGap: 'clamp(1rem, 2vw, 2rem)',
    mediaCompositionShift: 'clamp(0.5rem, calc(24.5% - 28.8vh), 4.75rem)',
    browser: {
      height: '92%',
      maxWidth: '94%',
      aspectRatio: '1.79',
      compactWidth: '96%',
      compactAspectRatio: '1.7',
    },
    mobileMediaWidth: 'clamp(10rem, 19vw, 16.5rem)',
    compactMobileMediaWidth: 'clamp(8.25rem, 34vw, 11.5rem)',
    deviceAspectRatio: '195 / 422',
    backgroundGridSize: 'clamp(40px, 4vw, 64px)',
    listGap: 'clamp(2.75rem, 6vw, 6rem)',
    infoPadding: 'clamp(1rem, 2vw, 2rem)',
    titleSize: 'clamp(1.65rem, 2.8vw, 2.75rem)',
    categorySize: 'clamp(0.88rem, 1vw, 0.98rem)',
  },
  process: {
    introTitleSize: 'clamp(3.15rem, 4.65vw, 5.1rem)',
    introTitleMobileSize: 'clamp(2.5rem, 11vw, 3.2rem)',
    introLineOffset: 'clamp(2.25rem, 5.5vw, 5rem)',
    introMobileLineOffset: 'clamp(0.5rem, 4vw, 1.25rem)',
    introDescriptionOffset: 'clamp(2.5rem, 6vw, 5.5rem)',
    introDescriptionMaxWidth: '34rem',
    introDescriptionWeight: 550,
    headingMarginBottom: 'clamp(4rem, 7vw, 7rem)',
    journeyStageWidth: '75rem',
    journeyStageHeight: 'clamp(32rem, 43vw, 38.75rem)',
    journeyStageTop: 'clamp(5.75rem, 12svh, 7.5rem)',
    journeyTrackRunway: '120svh',
    journeyProgressStart: 0.22,
    journeyProgressEnd: 0.67,
    journeyTerminalHoldEnd: 0.76,
    mobileJourneyWidth: '34rem',
    mobileJourneyHeight: 'clamp(68rem, 310vw, 78rem)',
    stepWidth: 'clamp(15rem, 20vw, 19rem)',
    stepCopyMaxWidth: '19rem',
    stepInactiveOpacity: 0.34,
    stepRevealDistance: 8,
    numberSize: 'clamp(3.75rem, 5.6vw, 5.75rem)',
    markerSize: '1rem',
    markerBorderWidth: '2px',
    markerContentGap: '1.35rem',
    markerHaloSize: '0.18rem',
    markerHaloCurrentScale: 1.26,
    markerHaloSettledScale: 1.4,
    pathBaseWidth: 1.5,
    pathProgressWidth: 2.5,
    stepTitleSize: 'clamp(1.4rem, 2vw, 1.82rem)',
    stepCopySize: 'clamp(0.96rem, 1vw, 1.01rem)',
  },
  signature: {
    sectionMinHeight: 'clamp(44rem, 62vw, 56rem)',
    contentMaxWidth: '42rem',
    contentNotebookMaxWidth: '36rem',
    titleSize: 'clamp(2.8rem, 4.2vw, 4.6rem)',
    titleMobileSize: 'clamp(2.5rem, 10.5vw, 3.25rem)',
    copyMaxWidth: '38rem',
    copyWeight: 530,
    logoWidth: 'clamp(28rem, 45vw, 43rem)',
    logoOffset: '58%',
    logoMobileWidth: 'min(82vw, 20rem)',
    signatureMarginTop: 'clamp(2.5rem, 4vw, 3.75rem)',
    nameSize: 'clamp(1.05rem, 1.15vw, 1.14rem)',
    roleSize: 'clamp(0.9rem, 0.96vw, 0.95rem)',
  },
  finalCta: {
    sectionPaddingBlock: 'clamp(5.5rem, 10vw, 10rem)',
    backgroundGridSize: 'clamp(40px, 4vw, 64px)',
    eyebrowLineWidth: 'clamp(1.25rem, 3vw, 2.5rem)',
  },
} as const;

// Durações e curvas compartilhadas de interação.
export const motion = {
  duration: {
    quick: '160ms',
    fast: '180ms',
    base: '200ms',
    medium: '220ms',
  },
  easing: {
    standard: 'ease',
  },
} as const;

export const withAlpha = (hex: string, alpha: number): string => {
  const normalized = hex.replace('#', '');
  const value = normalized.length === 3
    ? normalized.split('').map((character) => `${character}${character}`).join('')
    : normalized;

  return `rgba(${Number.parseInt(value.slice(0, 2), 16)}, ${Number.parseInt(value.slice(2, 4), 16)}, ${Number.parseInt(value.slice(4, 6), 16)}, ${alpha})`;
};
