# Generated by Django 5.2.6 on 2026-08-14 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=16)),
                ('project_type', models.CharField(choices=[('landing_page', 'Landing page'), ('institutional_site', 'Site institucional'), ('custom_solution', 'Solução personalizada'), ('support_or_evolution', 'Suporte ou evolução'), ('not_sure', 'Ainda não sabe')], max_length=32)),
                ('business_name', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField(blank=True, default='', max_length=4000)),
                ('source', models.CharField(choices=[('website', 'Website')], max_length=32)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('archived', 'Arquivado')], default='new', max_length=16)),
                ('privacy_policy_acknowledged', models.BooleanField(default=False)),
                ('privacy_policy_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
