# Generated by Django 5.2.6 on 2026-08-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_privacy_policy_version_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('in_progress', 'Em andamento'), ('delivered', 'Entregue'), ('maintenance', 'Manutenção'), ('archived', 'Arquivado')], default='new', max_length=16),
        ),
    ]
