# Generated by Django 5.2.6 on 2026-08-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='acquisition_source',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
